"""Initial migration

Revision ID: 9a62654d0a71
Revises: 
Create Date: 2025-02-15 03:46:03.150283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a62654d0a71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_languages_id'), ['id'], unique=False)

    op.create_table('language_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_language_id', sa.Integer(), nullable=True),
    sa.Column('target_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_language_id', 'target_language_id', name='unique_language_pair')
    )
    with op.batch_alter_table('language_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_language_pairs_id'), ['id'], unique=False)

    op.create_table('vocabularies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=True),
    sa.Column('translation', sa.String(), nullable=True),
    sa.Column('language_pair_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_pair_id'], ['language_pairs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'language_pair_id', name='unique_word_per_language_pair')
    )
    with op.batch_alter_table('vocabularies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabularies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabularies_word'), ['word'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabularies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabularies_word'))
        batch_op.drop_index(batch_op.f('ix_vocabularies_id'))

    op.drop_table('vocabularies')
    with op.batch_alter_table('language_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_language_pairs_id'))

    op.drop_table('language_pairs')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_id'))
        batch_op.drop_index(batch_op.f('ix_languages_code'))

    op.drop_table('languages')
    # ### end Alembic commands ###
