"""Add user and session models

Revision ID: e5fba5eb1a76
Revises: xxxxxxxxxxxx
Create Date: 2025-02-17 18:50:31.888312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fba5eb1a76'
down_revision: Union[str, None] = 'xxxxxxxxxxxx'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_languages_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_languages_id'), ['id'], unique=False)

    op.create_table('language_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_language_id', sa.Integer(), nullable=True),
    sa.Column('target_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_language_id', 'target_language_id', name='unique_language_pair')
    )
    with op.batch_alter_table('language_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_language_pairs_id'), ['id'], unique=False)

    op.create_table('vocabularies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('language_pair_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_pair_id'], ['language_pairs.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'language_pair_id', name='uix_word_language_pair')
    )
    with op.batch_alter_table('vocabularies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabularies_id'), ['id'], unique=False)

    op.create_table('vocabulary_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('language_pair_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_pair_id'], ['language_pairs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocabulary_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_groups_id'), ['id'], unique=False)

    op.create_table('vocabulary_group_association',
    sa.Column('vocabulary_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['vocabulary_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], ondelete='CASCADE')
    )
    op.create_table('vocabulary_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=True),
    sa.Column('correct_attempts', sa.Integer(), nullable=False),
    sa.Column('incorrect_attempts', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('mastered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocabulary_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_progress_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_progress_id'))

    op.drop_table('vocabulary_progress')
    op.drop_table('vocabulary_group_association')
    with op.batch_alter_table('vocabulary_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_groups_id'))

    op.drop_table('vocabulary_groups')
    with op.batch_alter_table('vocabularies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabularies_id'))

    op.drop_table('vocabularies')
    with op.batch_alter_table('language_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_language_pairs_id'))

    op.drop_table('language_pairs')
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_languages_id'))
        batch_op.drop_index(batch_op.f('ix_languages_code'))

    op.drop_table('languages')
    # ### end Alembic commands ###
