export { default as Dashboard } from './Dashboard'
export { default as Vocabulary } from './Vocabulary'
export { default as Sessions } from './Sessions'
export { default as Activities } from './Activities'
export { default as Settings } from './Settings' 